### ISSUE TITLE
Code is broken? Failed to dump SPR public key (code -199)

### ISSUE THREAD

**Issue by Hellangel1987** [maximkulkin/esp32-homekit-camera#108]
Code Builds good, upload is good still facing this issue. Tried all available Boards.

![image](https://user-images.githubusercontent.com/20953591/217816254-4e121f4e-f240-41b5-a86b-184460b81faa.png)

**Comment by Hellangel1987** [comment]
Update enabled more debug info and now get additional

crypto_ed25519_generate: Failed to generate key (code -199)

![image](https://user-images.githubusercontent.com/20953591/217826033-ec5b255c-0dc1-4071-83ea-f6d543a71dca.png)

**Comment by AchimPieters** [comment]
solution: git submodule update --remote --merge

**Comment by Hellangel1987** [comment]
thanks @AchimPieters issue solved
