### ISSUE TITLE
Crash when starting video stream - is video streaming still not implemented?

### ISSUE THREAD

**Issue by ziolelle** [maximkulkin/esp32-homekit-camera#11]
Sorry, probably is not a real issue. I saw an closed issue about not still implemented video streaming. Is it still so ?

**Comment by maximkulkin** [comment]
Yes, streaming still does not work and it’s development currently has been deprioritized.

**Comment by ziolelle** [comment]
ok, thank for the feedback,
Anyway.. my big compliments! ,really a good job, thank so much for your effort ! I appreciate so much your work
