### ISSUE TITLE
How To

### ISSUE THREAD

**Issue by iShortOne** [maximkulkin/esp32-homekit-camera#12]
Hi, thanks for this firmware.
I have a question, how I can flash it?
Thanks in advance!

**Comment by maximkulkin** [comment]
```shell
export ESPPORT=<port>
make menuconfig
make all
make flash
```

**Comment by massimo79** [comment]
@maximkulkin is a .bin file available? THANK YOU!!!

**Comment by maximkulkin** [comment]
The binary is not available, a) I do not generally do that; b) the code is not finished yet. Also, there are different pin layouts for different modules. I might release binaries once the project is finished.
