### ISSUE TITLE
Incomplete boot - pairing code?

### ISSUE THREAD

**Issue by KissmanCZ** [maximkulkin/esp32-homekit-camera#13]
Hello Maxim, I just flashed your FW to my ESP32 and I am stucked on this:

```
>>> HomeKit: Starting server
>>> HomeKit: Using existing accessory ID: AD:B3:70:E8:D9:36
>>> HomeKit: Configuring mDNS
```

I can see cam in my HomeKit, but I am not able to add, becuse I am missing pairing code. I think that boot of my ESP32 is not complete?

**Comment by beatpaul** [comment]
Same problem for me?

**Comment by KissmanCZ** [comment]
Enabled homekit debug mode:

```
>>> HomeKit: Starting server
>>> HomeKit: Using existing accessory ID: AD:B3:70:E8:D9:36
>>> HomeKit: Configuring mDNS
>>> homekit_run_server: Staring HTTP server

```

**Comment by KissmanCZ** [comment]
Ok, tried 11111111 code and cam is connected now :)
