### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by pwallner** [maximkulkin/esp32-homekit-camera#18]
During waiting for my ordered esp32 I have some ideas:
1. On first setup a wifi hotspot running on esp32 to connect via PC directly to show a webpage to enter SSID and passwort of router,(which will be saved, maybe on SD card if not possible in flash), then the esp32 (maybe with a reboot) will connect to home wifi
2. after connecting to wifi, the cam is reachable via webinterface to see the qr-code for scanning and connecting to homekit. Maybe the possibility to enter the password (eg 123-45-678) on webinterface which is stored on SD if not possible in flash
3. saving of images on SD card on motion detection

**Comment by maximkulkin** [comment]
Unfortunately, I do not plan to implement any of that so see no reason to keep it around.
