### ISSUE TITLE
Re-add cam to homekit

### ISSUE THREAD

**Issue by pwallner** [maximkulkin/esp32-homekit-camera#21]
I have removed the cam in homekit, now I would like to re-add it, but it is not listed in homekit, so how can I find out the code for manual entering?

**Comment by maximkulkin** [comment]
Did you remove it while camera being offline or you being off-network? Then the camera still thinks it is paired.. You need to erase HomeKit settings from accessory flash (either by using esptool to erase particular sector or just erase all and re-flash).

**Comment by pwallner** [comment]
Yes I did, and the camera still thinks it's paired.

So I did `make erase_flash` 
Then...
` make flash`  and the cam is back again...

Thank you for the hint
