### ISSUE TITLE
Faster snapshot rate

### ISSUE THREAD

**Issue by VojGin** [maximkulkin/esp32-homekit-camera#25]
Hey there,

I read that video streaming does not currently work #17 #20 and is deprioritized #22.
At the current state, the camera makes a snapshot every 10 seconds. Is there a way to make the delay shorter, so the snapshot rate would be let's say 1 snapshot per second?
Tried to look it up myself in the code, but didn't find anything I would feel confident changing.

Thanks for the answer!

**Comment by maximkulkin** [comment]
No, snapshot is requested by iOS, you can not change period.
