### ISSUE TITLE
Missing homekit rule

### ISSUE THREAD

**Issue by GermanSheepDog** [maximkulkin/esp32-homekit-camera#3]
Hello,

I started from scratch to compile:
- git clone https://github.com/maximkulkin/esp32-homekit-camera.git
- Menuconfig: Config serial flasher
- Menuconfig: ESP32 Homekit camera: Config STA, wifi-SSID and wifi password

I got this message:
```
...
CC build/lwip/port/esp32/debug/lwip_debug.o
AR build/lwip/liblwip.a
make: *** No rule to make target `component-homekit-build', needed by `component-main-build'.  Stop.
Pg1:esp32-homekit-camera <username>$ 
```

**Comment by maximkulkin** [comment]
Instead of plain `git clone` you need to do `git clone --recurse-submodules https://github.com/maximkulkin/esp32-homekit-camera.git`
