### ISSUE TITLE
M5Stack Fish-Eyes CameraF ov2640

### ISSUE THREAD

**Issue by fmoreni** [maximkulkin/esp32-homekit-camera#32]
Hello,

It does not seem to work on the M5Stack Fish-Eyes CameraF https://m5stack.com/products/fish-eye-camera-module-ov2640.
Do not enable AP mode for connection!

Does anyone have any tips?

make monitor
Toolchain path: /root/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
Toolchain version: crosstool-ng-1.22.0-80-g6c4433a
Compiler version: 5.2.0
Python requirements from /root/esp/esp-idf/requirements.txt are satisfied.
MONITOR
--- idf_monitor on /dev/ttyUSB0 115200 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x33 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:6124
load:0x40078000,len:10180
load:0x40080400,len:6660
entry 0x40080764
I (29) boot: ESP-IDF v3.2.2 2nd stage bootloader
I (29) boot: compile time 01:26:36
I (31) boot: Enabling RNG early entropy source...
I (33) boot: SPI Speed      : 40MHz
I (38) boot: SPI Mode       : DIO
I (42) boot: SPI Flash Size : 4MB
I (46) boot: Partition Table:
I (49) boot: ## Label            Usage          Type ST Offset   Length
I (56) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (64) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (71) boot:  2 factory          factory app      00 00 00010000 001f0000
I (79) boot: End of partition table
I (83) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0xa8ce4 (691428) map
I (334) esp_image: segment 1: paddr=0x000b8d0c vaddr=0x3ffb0000 size=0x03bec ( 15340) load
I (340) esp_image: segment 2: paddr=0x000bc900 vaddr=0x40080000 size=0x00400 (  1024) load
0x40080000: _WindowOverflow4 at /root/esp/esp-idf/components/freertos/xtensa_vectors.S:1779

I (341) esp_image: segment 3: paddr=0x000bcd08 vaddr=0x40080400 size=0x03308 ( 13064) load
I (355) esp_image: segment 4: paddr=0x000c0018 vaddr=0x400d0018 size=0x118368 (1147752) map
0x400d0018: _stext at ??:?

I (761) esp_image: segment 5: paddr=0x001d8388 vaddr=0x40083708 size=0x131e8 ( 78312) load
0x40083708: psram_cmd_recv_start at /root/esp/esp-idf/components/esp32/spiram_psram.c:273 (discriminator 5)

I (807) boot: Loaded app from partition at offset 0x10000
I (807) boot: Disabling RNG early entropy source...
I (809) spiram: Found 32MBit SPI RAM device
I (812) spiram: SPI RAM mode: flash 40m sram 40m
I (817) spiram: PSRAM initialized, cache is in low/high (2-core) mode.
I (824) cpu_start: Pro cpu up.
I (828) cpu_start: Starting app cpu, entry point is 0x4008138c
0x4008138c: call_start_cpu1 at /root/esp/esp-idf/components/esp32/cpu_start.c:246

I (0) cpu_start: App cpu up.
I (1729) spiram: SPI SRAM memory test OK
I (1729) heap_init: Initializing. RAM available for dynamic allocation:
I (1730) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (1736) heap_init: At 3FFBBA18 len 000245E8 (145 KiB): DRAM
I (1742) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (1748) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (1755) heap_init: At 400968F0 len 00009710 (37 KiB): IRAM
I (1761) cpu_start: Pro cpu start user code
I (1766) spiram: Adding pool of 4096K of external SPI memory to heap allocator
I (110) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (111) spiram: Reserving pool of 32K of internal memory for DMA/internal allocations
I (201) wifi: wifi driver task: 3ffcb5ec, prio:23, stack:3584, core=0
I (201) wifi: wifi firmware version: 693c7b6
I (201) wifi: config NVS flash: enabled
I (211) wifi: config nano formating: disabled
I (211) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (221) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (251) wifi: Init dynamic tx buffer num: 32
I (251) wifi: Init data frame dynamic rx buffer num: 32
I (251) wifi: Init management frame dynamic rx buffer num: 32
I (261) wifi: Init management short buffer num: 32
I (261) wifi: Init static tx buffer num: 16
I (271) wifi: Init static rx buffer size: 1600
I (271) wifi: Init static rx buffer num: 10
I (271) wifi: Init dynamic rx buffer num: 32
I (351) phy: phy_version: 4008, 544f89f, Jan 24 2019, 14:54:06, 0, 0
I (351) wifi: mode : sta (b4:e6:2d:a4:4f:f5)
STA start
STA disconnected
STA disconnected
STA disconnected
STA disconnected
STA disconnected
STA disconnected
STA disconnected
STA disconnected
STA disconnected
STA disconnected
STA disconnected

**Comment by maximkulkin** [comment]
It’s not supposed to: right now firmware is configured to connect to a WiFi network that you set up through menuconfig.
