### ISSUE TITLE
homekit encoding of video attributes

### ISSUE THREAD

**Issue by HomeACcessoryKid** [maximkulkin/esp32-homekit-camera#4]
Current code
    ```tlv_add_integer_value(video_attributes, 3, 2, CAMERA_FRAME_RATE);  // Frame rate```

Apple spec specifies length as 1, not 2
```
Frame rate | 3 | 1 | Maximum frame rate
```

ALSO:
```    tlv_add_integer_value(audio_codec, 1, 1, 3);```
Spec length says 2, not 1

**Comment by maximkulkin** [comment]
I think that field was mainly why I had to implement `tlv_add_integer_value()` explicitly requiring field size. I will recheck that, but so far it worked OK with iOS controller.
