### ISSUE TITLE
Couldn't compile

### ISSUE THREAD

**Issue by okanduzyel** [maximkulkin/esp32-homekit-camera#46]
Hi,

I cloned "esp32-homekit-camera" example inside esp32-homekit-camera folder which I created with that path **_"esp-homekit-demo/examples/esp32-homekit-camera"_**

I cloned with that command -> _**git clone --recursive https://github.com/maximkulkin/esp32-homekit-camera.git .**_

Then, my direction like that:
	components
	main
	.gitignore
	.gitmodules
	LICENSE
	Makefile
	README.md	
	esp32-camera.patch
	
I tried to make menuconfig command got that:
make: *** test: No such file or directory. Stop. 

I tried same thing inside of main folder and got same respond. 

**make -C . test** didn't work for me. **make -C . erase_flash** either. What do I miss? Now, my linux machine can compile and flash any esp8266. Should I install anything for esp32?

**Addition:** 

I guess, I need to install ESP-IDF? I am new in linux environment, I don't want to destroy my esp8266 files and its compiling capability.

Can you help me line by line which codes should I run to install until compiling esp32-homekit-camera example?

**Comment by AchimPieters** [comment]
https://github.com/maximkulkin/esp-homekit-demo/wiki/Build-instructions-ESP32

**Comment by okanduzyel** [comment]
Hi, 

I tried them but I couldn't again. I am stuck in first step of https://docs.espressif.com/projects/esp-idf/en/latest/get-started/

I had solved that for esp8266 with this video https://www.youtube.com/watch?v=QBj8OLig8Kg

There is a vagrant file which contains line by line codes what It need to install. 

is there any vagrant file like above for esp32?

**Comment by AchimPieters** [comment]
@okanduzyel maybe this will help:

https://www.studiopieters.nl/esp32-toolchain-installation/

**Comment by okanduzyel** [comment]
Unfortunately, I am currently working on Windows computer and vagrant ubuntu. 🙁

**Comment by AchimPieters** [comment]
Maybe this is a solution: https://www.studiopieters.nl/esp-homekit-sdk-ubuntu-on-virtualbox/

**Comment by okanduzyel** [comment]
I wish that There were a solution as .bin files (for specific boards i.e ai thinker esp-cam), flash esp32 with appropriate .bin file for my board and at the end, connect it wifi like sonoff...

@maximkulkin

**Comment by AchimPieters** [comment]
Welk maybe this is not for you.

**Comment by okanduzyel** [comment]
Maybe, Maybe not.

Because, I did! This helped so much for me https://www.youtube.com/watch?v=EjfhrAFWVPM&t=379s

People who like me, is not a programmer, will live these problems. 

Please start to read that instructions -> https://docs.espressif.com/projects/esp-idf/en/latest/get-started/linux-setup.html

Something are different that video. So you will deal with a few problem. when google the problem individually, you can find its solution. I dealt with more than 15-20 problems and now, I can erase-flash esp32.

Thank you for your helping @AchimPieters
