### ISSUE TITLE
Compiling error on macOS

### ISSUE THREAD

**Issue by okanduzyel** [maximkulkin/esp32-homekit-camera#49]
Hi,

I have got that error on three different ubuntu machine: https://github.com/maximkulkin/esp32-homekit-camera/issues/47

So, I tried to compile it on macOS. Now, I have got that error: 

```
/Users/okanduzyel/esp/esp32-homekit-camera/components/esp32-camera/driver/xclk.c: In function 'camera_enable_out_clock':
/Users/okanduzyel/esp/esp32-homekit-camera/components/esp32-camera/driver/xclk.c:36:12: error: 'ledc_channel_config_t {aka struct <anonymous>}' has no member named 'hpoint'
     ch_conf.hpoint = 0;
            ^
make[1]: *** [driver/xclk.o] Error 1
make: *** [component-esp32-camera-build] Error 2
```

**Comment by maximkulkin** [comment]
I think what is happening is Espressif changing their APIs in latest esp-idf. I suggest you stick with esp-idf 4.0 version.

**Comment by okanduzyel** [comment]
> I think what is happening is Espressif changing their APIs in latest esp-idf. I suggest you stick with esp-idf 4.0 version.

which version do you prefer to or you can compile? I install it according to its web site and that web site contains always updated version.

**Comment by okanduzyel** [comment]
https://docs.espressif.com/projects/esp-idf/en/v3.2.3/get-started/index.html

worked for me. Thanks a lot!

**Comment by leovj** [comment]
Thank Maxim!
Do you mean 3.0 version?

Leo

________________________________
Da: Maxim Kulkin <notifications@github.com>
Inviato: martedì 3 dicembre 2019 20:05
A: maximkulkin/esp32-homekit-camera <esp32-homekit-camera@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Oggetto: Re: [maximkulkin/esp32-homekit-camera] Compiling error on macOS (#49)


I think what is happening is Espressif changing their APIs in latest esp-idf. I suggest you stick with esp-idf 4.0 version.
