### ISSUE TITLE
Compiler options missing

### ISSUE THREAD

**Issue by nixmeer** [maximkulkin/esp32-homekit-camera#64]
Hello :) 
I can't find "Camera configuration" and "HomeKit" under "component config". "ESP32-specific" shows up. What am doing wrong?

Best

Jan

**Comment by jarredthejellyfish** [comment]
Did you use ` git clone --recurse-submodules` while cloning the repository?

**Comment by nixmeer** [comment]
That fixed it! Thank you a lot! Should I have guessed using the `--recurse-submodules` option or is it documented anywhere?

**Comment by nixmeer** [comment]
Note: In addition to the described options in the readme, I had to change the following options in menuconfig:

- `Support array `rtc_gpio_desc` for ESP32` = **check**
- `Enable FreeRTOS static allocation API` = **check**
