### ISSUE TITLE
menuconfig

### ISSUE THREAD

**Issue by mohammadrkh** [maximkulkin/esp32-homekit-camera#77]
Hi
I’m a beginner 
There is a problem with menu config
1- I’ve done everything that is on readme but when I use make menuconfig command I get this
“'make' is not recognized as an internal or external command, operable program or batch file.“
2- So I used idf.py menuconfig and I get this:
"CMakeLists.txt not found in project directory"
3- to fix that I added one the example’s CMakeLists.txt to esp32-homekit-camera folder then use idf.py menuconfig and it worked and also have camera configuration and HomeKit under component config but it doesn’t have the esp32 homekit camera and it doesn’t have RTCIO Configuration
Thanks!

**Comment by AR-Tawil** [comment]
Hi
I'm getting the following error. Can you please give me some guidance on how fix this error so i can compile my code?
Thank you for your help.
Tawil


id124659@appss-MacBook-Pro-3697 esp-idf % idf.py menuconfig 
The following Python requirements are not satisfied:
gdbgui>=0.13.2.0
To install the missing packages, please run "/Users/id124659/esp32/esp-idf/install.sh"
Diagnostic information:
    IDF_PYTHON_ENV_PATH: /Users/id124659/.espressif/python_env/idf4.3_py3.8_env
    Python interpreter used: /Users/id124659/.espressif/python_env/idf4.3_py3.8_env/bin/python

ESP-IDF v4.3-dev-907-g6c17e3a64

**Comment by mohammadrkh** [comment]
@maximkulkin 
I need help

**Comment by maximkulkin** [comment]
Well, in general, I do not recommend this to beginners. You need to have Make installed. Also, it seems that you're running some old ESP_IDF (pre-4.1) which does not have that option (and you might need to patch stuff to other components). Or upgrade to latest ESP_IDF

**Comment by mohammadrkh** [comment]
Tnx!
I did the ￼whole process several times and it finally worked just before I read your comment 
Tnx again
