### ISSUE TITLE
Failed to dump SPR public key (code -199)

### ISSUE THREAD

**Issue by camelbo** [maximkulkin/esp32-homekit-camera#98]
Hello,

i am not able to connect the cam with error:
"Failed to dump SPR public key (code -199)"

At First Startup, i had:
>>> HomeKit: Generated new accessory ID: DC:14:2C:7B:C7:71
!!! HomeKit: Failed to generate accessory key
>>> HomeKit: Configuring mDNS

What am i doing wrong?

**Comment by AchimPieters** [comment]
solution: git submodule update --remote --merge

**Comment by camelbo** [comment]
THANK YOU SO MUCH ACHIM!!!!

Working

**Comment by phuzybuny** [comment]
Same problem; fix also worked for me.
